# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT
#

services:
  postgres:
    image: postgres:15.8-alpine
    hostname: localhost
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "status-registry-db"
    ports:
      - "5290:5432"
